### ISSUE TITLE
ipset names must be different for ipv6 and ipv4 ipsets

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/kube-router#2]
ipv4 ipsets require `family inet` and ipv6 ipsets require `family inet6`

Therefore, we need to create different ipsets for each type of address. To do so, the SHA that is part of the ipset name needs to be different and thus, we should include the ipFamily to it.

At the end of `pkg/controllers/netpol/policy.go`, we should add the ipFamily parameter to the SHA calculation to the first three functions:
```
func networkPolicyChainName(namespace, policyName string, version string, ipFamily api.IPFamily) string {
        hash := sha256.Sum256([]byte(namespace + policyName + version + string(ipFamily)))
        encoded := base32.StdEncoding.EncodeToString(hash[:])
        return kubeNetworkPolicyChainPrefix + encoded[:16]
}

func policySourcePodIPSetName(namespace, policyName string, ipFamily api.IPFamily) string {
        hash := sha256.Sum256([]byte(namespace + policyName + string(ipFamily)))
        encoded := base32.StdEncoding.EncodeToString(hash[:])
        return kubeSourceIPSetPrefix + encoded[:16]
}

func policyDestinationPodIPSetName(namespace, policyName string, ipFamily api.IPFamily) string {
        hash := sha256.Sum256([]byte(namespace + policyName + string(ipFamily)))
        encoded := base32.StdEncoding.EncodeToString(hash[:])
        return kubeDestinationIPSetPrefix + encoded[:16]
```
Of course, the places where we are calling these functions must be changed to include ipFamily (it's pretty easy as all calls to those functions have access to ipFamily)

**Comment by vadorovsky** [comment]
Fixed and pushed

**Comment by manuelbuil** [comment]
You forgot to add `+ string(ipFamily)))` to:
- policySourcePodIPSetName
- policyDestinationPodIPSetName

**Comment by vadorovsky** [comment]
Fixed and pushed
